// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdywokyjvijqcvofirij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkeXdva3lqdmlqcWN2b2ZpcmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTIyMzMsImV4cCI6MjA3MzIyODIzM30.WL0hSEiF9phsCXdv3hQNTaBIg2FJ0AR12rR7_pzbg1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});